// src/components/Section.tsx
import type { LucideIcon } from 'lucide-react'
import React from 'react'

export function Title({
  title,
  icon
}: {
  title: string
  icon?: React.ReactElement<React.ComponentProps<LucideIcon>>
}) {
  return (
    <div className='flex items-center px-4 sm:px-6 md:px-10 gap-2 text-2xl mt-20 mb-5'>
      {React.isValidElement(icon) && icon}
      <h3 className='uppercase text-left'>{title}</h3>
    </div>
  )
}

export function Section({
  id,
  children
}: {
  id: string
  children: React.ReactNode
}) {
  return <section id={id}>{children}</section>
}

export function Body({ children }: { children: React.ReactNode }) {
  return (
    <div className='flex flex-col gap-5 px-4 sm:px-6 md:px-10'>{children}</div>
  )
}

export default { Section, Title, Body }

// src/lib/components/Section.svelte
<script lang="ts">
	import type { Component, Snippet } from 'svelte'

	let { icon, title, children }: { icon?: Component; title: String; children?: Snippet } = $props()
</script>

<section class="w-full max-w-2xl">
	<div class="mb-1 flex items-center gap-2">
		{#if icon}
			{@const Icon = icon}
			<Icon class="stroke-zinc-900 dark:stroke-zinc-300" size="18" />
		{/if}
		<h3>{title}</h3>
	</div>
	<hr class="mb-2 w-4/12 border-b-1 border-zinc-900 dark:border-zinc-300" />
	<div class="flex grow flex-col gap-3">
		{@render children?.()}
	</div>
</section>
